app:
  environment: prod

paths:
  logs: D:\Produccion\Taller-app\empresa\logs
  logos: D:\Produccion\Taller-app\empresa\logos
  imagenes: D:\Produccion\Taller-app\empresa\imagenes
  salida: D:\Produccion\Taller-app\empresa\salida

logging:
  level:
    root: INFO