app:
  environment: dev

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/taller_bd_desa
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration

paths:
  logs: D:\Proyectos\Logs_proyectos\taller_app
  logos: D:\Proyectos\almacenamiento\taller_app\empresa\logos
  imagenes: D:\Proyectos\almacenamiento\taller_app\empresa\images
  salida: D:\Proyectos\almacenamiento\taller_app\empresa\salida

logging:
  level:
    root: INFO
  file:
    path: ${paths.logs}
